name: Lint
on:
  pull_request:
  push:
jobs:
  run_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".node-version"
      - name: Install dependencies
        run: npm ci
      - name: Run ESLint
        run: npm run lint
